version: '3'
services:
  db:
    container_name: docker-compose-django-db
    image: postgres:11.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    container_name: docker-compose-django-web
    build: .
    image: docker-compose-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
